### ISSUE TITLE
Command line args available in scope (in particular temporary-directory)

### ISSUE THREAD

**Issue by Unode** [luispedro/ngless#16]
I've recently missed having access to $TMPDIR or `--temporary-directory` as part of the script.
I couldn't find any way to access the environment or the command line arguments besides `ARGV`.

I'm currently using `ARGV` to workaround this limitation but calling ngless with: `ngless script.ngl $TMPDIR`.

As related-questions (maybe FAQ candidates): 
* Is there any builtin function that lists all the variables in the existing scope (akin to Python's `locals()` / `globals()`?
* The documentation also doesn't explicitly list variables implicitly defined. Looking at the code I find `STDIN`, `STDOUT` and `ARGV`. Are there others?

**Comment by luispedro** [comment]
What is the use case of exporting TMPDIR to the environment? If you want to write some output there, then using ARGV feels very logical to me, actually.

*

I agree on the documentation issue. Off the top of my head, I don't think there are other builtins, although the "batch" module defines some ones.

**Comment by Unode** [comment]
I rely more on $TMPDIR these days which is only known at runtime.
Recently I've also tried the [sbcast](https://slurm.schedmd.com/sbcast.html) feature on SLURM nodes to compartmentalize IO.

`sbcast` recommends using `$TMPDIR` for databases and such so I was going for:

    DB = TMPDIR + "/database.fna"

at the moment I do:

    TMPDIR = ARGV[1]
    DB = TMPDIR + "/database.fna"

**Comment by luispedro** [comment]
I mistakenly deleted a comment (Sorry) about the use of SLURM's [sbcast](https://slurm.schedmd.com/sbcast.html) utility to put databases in `$TMPDIR.`

**Comment by luispedro** [comment]
sbcast is indeed a valid use case.

I have considered introducing a database search path feature. I'm afraid of making it "too magical", but this might be a more general solution.

**Comment by luispedro** [comment]
I am going to fix the documentation on constants.

I also think that a database search path is a good feature, which will address this and other cases in a generic way.
