### ISSUE TITLE
ofile= doesn't use output_directory

### ISSUE THREAD

**Issue by Unode** [luispedro/ngless#17]
Currently output generated by `collect()` is saved to the current directory instead of the directory specified via `-o output_directory`.

    ngless -o output script.ngl

where script contains:

    collect(count(mapped, features=['seqname']),
        current=sample,
        allneeded=readlines('input.txt'),
        ofile='output.tsv'

produces 'output.tsv' instead of 'output/output.tsv'.

**Comment by luispedro** [comment]
Let me think more about this.

The` --output-directory` argument where to write the semi-maintained HTML output as well as some automatically collected statistics. At the very least, this option is badly named. `--html-report-output` may be a better description?

In any case, resolving how to do meaningful stats output &c in the presence of `collect()` and friends is something to figure out before version 1.0.

**Comment by Unode** [comment]
I see now that in previous uses I actually prepended "outputs/" to my output locations.
So this is broader, not just affecting `collect()` but `ofile=` in general. If this is a target.
