### ISSUE TITLE
Update samtools

### ISSUE THREAD

**Issue by luispedro** [luispedro/ngless#40]
This should just be a matter of updating the URLs in the `Makefile`, but sometimes we need to change the configuration options.

**Comment by unode** [comment]
References in https://github.com/luispedro/ngless/blob/f241513680371febf45c9ed0a2e07d8e5865f9fb/NGLess/Dependencies/embedded.c#L6
will also need to be updated as the tool currently used to generate them (`xxd`) includes the filename as part of the output.
