### ISSUE TITLE
Prodigal produces different output depending on GCC version used to compile it

### ISSUE THREAD

**Issue by unode** [luispedro/ngless#45]
This is not an NGLess bug but is meant to track progress upstream.

https://github.com/hyattpd/Prodigal/issues/34

This issue was first noticed when tests on our alpine build-image failed due to a different output but passed on the ubuntu-image.

**Comment by luispedro** [comment]
We can potentially add a patch on the NGLess side.

**Comment by luispedro** [comment]
I think patching it on our side fixes it. When we upgrade prodigal, we can check if the patch is still needed.
